Lab1 by Anatoliy Baskakov
innopolis-devops/labs pull request #12
Opened 2022-09-01 09:19 UTC by Anatolay

2022-09-01 09:30 UTC, bragov4ik requested changes

2022-09-01 09:30 UTC, bragov4ik commented on app_haskell/LICENSE
> +Copyright Author name here (c) 2022
```suggestion
Copyright Anatoliy Baskakov (c) 2022
```
Also I'm not sure this license is applicable since it's a work done in the scope of university course which is licensed under our agreements with the university (dushnilovo da)

2022-09-01 09:30 UTC, bragov4ik commented on app_haskell/msc.cabal
> +author:         Author name here
```suggestion
author:         Anatoliy Baskakov
```

2022-09-01 09:30 UTC, bragov4ik commented on app_haskell/LICENSE
> +    * Neither the name of Author name here nor the names of other
```suggestion
    * Neither the name of Anatoliy Baskakov here nor the names of other
```

2022-09-01 09:30 UTC, bragov4ik commented on app_haskell/msc.cabal
> +copyright:      2022 Author name here
```suggestion
copyright:      2022 Anatoliy Baskakov
```

2022-09-01 09:30 UTC, bragov4ik commented on app_haskell/package.yaml
> +author:              "Author name here"
```suggestion
author:              "Anatoliy Baskakov"
```

2022-09-01 09:30 UTC, bragov4ik commented on app_haskell/msc.cabal
> +description:    Please see the README on GitHub at <https://github.com/githubuser/msc#readme>
default link

2022-09-01 09:30 UTC, bragov4ik commented on app_haskell/msc.cabal
> +description:    Please see the README on GitHub at <https://github.com/githubuser/msc#readme>
same for the following lines

2022-09-01 09:30 UTC, bragov4ik commented on app_python/PYTHON.md
> +3. Do not forget to add to `.gitignore` python-related files and folders, e.g. `__pycache__`
I'd suggest not inventing your own `.gitignore` and use the [common one for Python](https://github.com/github/gitignore/blob/main/Python.gitignore)

2022-09-01 09:30 UTC, bragov4ik commented on app_python/app/main.py
> +        "location": "Samara"
We were asked to do Moscow (GMT+3) timezone, not Samara (GMT+4)

2022-09-02 14:56 UTC, sevenzing commented on app_python/app/main.py
> +    components = str(time).split(" ")
use `datetime.strptime` for converting time to string, as you did above

2022-09-02 14:57 UTC, sevenzing approved these changes

2022-09-05 20:30 UTC, Ilya-Kolomin reviewed
Review done

2022-09-05 20:30 UTC, Ilya-Kolomin commented on app_python/app/main.py
> +    msc_time = current_time - timedelta(hours=1)
Why do you harden the logic? Why not to take directly Moscow time?

2022-09-06 08:49 UTC, pminina01 approved these changes
Good

2022-09-12 23:18 UTC, closed without merging