Lab3. Iskander Bakhtiyarov
innopolis-devops/labs pull request #153
Opened 2022-09-16 16:22 UTC by Feyd-Rauth

2022-09-17 16:03 UTC, sevenzing approved these changes

2022-09-17 19:50 UTC, Anatolay requested changes

2022-09-17 19:50 UTC, Anatolay commented on .github/workflows/python.yml
> +    - uses: actions/setup-go@v1
What is "setup-go" needed for? I can only see python project here

2022-09-17 19:50 UTC, Anatolay commented on .github/workflows/python.yml
> +    - uses: actions/setup-go@v1
Same here, why is go installed?

2022-09-17 19:50 UTC, Anatolay commented
Please, make a PR from lab3 to lab2 locally so that it is easier to see changes

2022-09-19 14:17 UTC, Feyd-Rauth commented on .github/workflows/python.yml
> +    - uses: actions/setup-go@v1
Indeed. My bad

2022-09-19 15:19 UTC, Anatolay approved these changes

2022-09-19 23:47 UTC, pminina01 approved these changes

2022-09-20 07:14 UTC, bragov4ik approved these changes

2022-09-20 07:20 UTC, sevenzing approved these changes

2022-09-20 09:06 UTC, Ilya-Kolomin approved these changes

2022-09-28 00:47 UTC, closed without merging