Lab2
innopolis-devops/labs pull request #17
Opened 2022-09-03 11:10 UTC by sevenzing

2022-09-04 15:10 UTC, Feyd-Rauth commented
LGTM

2022-09-04 15:11 UTC, Feyd-Rauth approved these changes

2022-09-04 17:46 UTC, bragov4ik requested changes

2022-09-04 17:46 UTC, bragov4ik commented on docker-compose.yml
> +  app_golang:
```suggestion
  app_rust:
```

2022-09-12 19:08 UTC, Ilya-Kolomin approved these changes
Review OK👍

2022-09-12 19:08 UTC, Ilya-Kolomin commented on app_python/Dockerfile
> +ENTRYPOINT ["gunicorn", "app:app", "-b", "0.0.0.0:4444"]
Consider not running the app as `root` user.

2022-09-12 19:08 UTC, Ilya-Kolomin commented on app_rust/Dockerfile
> +FROM ubuntu:20.04 as run
1. Better to specify more concrete version
2. Ubuntu image is not that light-weight for running the production

2022-09-12 20:44 UTC, bragov4ik approved these changes

2022-09-13 08:03 UTC, pminina01 approved these changes

2022-09-16 20:53 UTC, closed without merging