Lab5
innopolis-devops/labs pull request #285
Opened 2022-10-02 12:40 UTC by sevenzing

2022-10-03 17:02 UTC, Feyd-Rauth approved these changes

2022-10-03 19:18 UTC, Anatolay requested changes

2022-10-03 19:18 UTC, Anatolay commented on ansible/inventory/default.yml.aboba
> +# test:
Probably this shouldn't be committed

2022-10-03 23:10 UTC, pminina01 approved these changes

2022-10-04 06:57 UTC, Ilya-Kolomin approved these changes
Review OK 👍

2022-10-04 06:57 UTC, Ilya-Kolomin commented on ansible/ANSIBLE.md
> +4. using Lab4 code, create yandex cloud VM using `tf apply`. Also I decided to ssh this VM and run `sudo apt-get update && sudo apt-get upgrade`, but I think it's optional.
Actually, docker role performs apt update, so you do not need to do this.

2022-10-04 08:27 UTC, bragov4ik approved these changes

2022-10-15 12:59 UTC, closed without merging