Lab5. Iskander Bakhtiyarov
innopolis-devops/labs pull request #296
Opened 2022-10-03 16:46 UTC by Feyd-Rauth

2022-10-03 23:11 UTC, pminina01 approved these changes

2022-10-04 06:58 UTC, Ilya-Kolomin approved these changes
Review OK 👍

2022-10-04 07:12 UTC, sevenzing approved these changes

2022-10-04 08:29 UTC, bragov4ik requested changes
No PR from lab5 to lab4

2022-10-04 09:04 UTC, bragov4ik approved these changes

2022-10-15 12:53 UTC, closed without merging