Lab6
innopolis-devops/labs pull request #335
Opened 2022-10-05 15:28 UTC by bragov4ik

diff: https://github.com/bragov4ik/devops/pull/9

2022-10-09 14:54 UTC, sevenzing approved these changes

2022-10-10 12:34 UTC, Feyd-Rauth requested changes

2022-10-10 12:34 UTC, Feyd-Rauth commented on ansible/ANSIBLE.md
> +$ ansible-playbook playbooks/dev/main.yml --diff
```suggestion
$ ansible-playbook playbooks/python/main.yml --diff
```

2022-10-10 20:26 UTC, Anatolay approved these changes

2022-10-10 23:26 UTC, pminina01 approved these changes

2022-10-11 06:02 UTC, Feyd-Rauth approved these changes

2022-10-11 11:48 UTC, Ilya-Kolomin approved these changes
Review OK 👍

2022-10-12 12:49 UTC, bragov4ik commented on ansible/ANSIBLE.md
> +$ ansible-playbook playbooks/dev/main.yml --diff
damn I forgor ☠️

2022-10-28 18:58 UTC, closed without merging