Lab6
innopolis-devops/labs pull request #342
Opened 2022-10-09 14:52 UTC by sevenzing

see diff sevenzing#2

2022-10-10 12:34 UTC, Feyd-Rauth requested changes

2022-10-10 12:34 UTC, Feyd-Rauth commented on ansible/roles/docker/tasks/setupDebian.yml
> +    state: present
```suggestion
    state: present
    update_cache: yes
```

2022-10-10 20:26 UTC, Anatolay approved these changes

2022-10-10 23:01 UTC, Feyd-Rauth approved these changes

2022-10-10 23:26 UTC, pminina01 approved these changes

2022-10-11 07:35 UTC, bragov4ik approved these changes

2022-10-11 11:51 UTC, Ilya-Kolomin approved these changes
Review OK 👍

2022-10-28 19:40 UTC, closed without merging