lab 1
innopolis-devops/labs pull request #5
Opened 2022-08-30 17:20 UTC by sevenzing

> <img width="105" alt="image" src="https://user-images.githubusercontent.com/41516657/187502284-0b915386-5a80-49cd-873c-c0d0772893ee.png">

> <img width="169" alt="image" src="https://user-images.githubusercontent.com/41516657/187502251-bb8aaffe-b48a-475d-a548-da5fe3ca09af.png">

2022-08-30 18:04 UTC, ntdesmond commented
> > <img alt="image" width="105" src="https://user-images.githubusercontent.com/41516657/187502284-0b915386-5a80-49cd-873c-c0d0772893ee.png">
> 
> > <img alt="image" width="169" src="https://user-images.githubusercontent.com/41516657/187502251-bb8aaffe-b48a-475d-a548-da5fe3ca09af.png">

у меня больше хихихи

2022-08-31 18:51 UTC, Ilya-Kolomin approved these changes
Review OK👍

2022-08-31 18:51 UTC, Ilya-Kolomin commented on app_python/pyproject.toml
> +name = "currenTTime"
Small typo :)

2022-09-01 09:11 UTC, bragov4ik requested changes
LGTM besides a typo

2022-09-01 09:11 UTC, bragov4ik commented on app_python/PYTHON.md
> ++ use EVN variables to configure your app without rebuilding
```suggestion
+ use ENV variables to configure your app without rebuilding
```

2022-09-01 10:48 UTC, bragov4ik approved these changes
LGTM

2022-09-06 08:47 UTC, pminina01 approved these changes
Good

2022-09-06 12:46 UTC, Anatolay approved these changes

2022-09-12 22:32 UTC, closed without merging