Lab1 Polina Minina
innopolis-devops/labs pull request #56
Opened 2022-09-05 18:22 UTC by pminina01

2022-09-05 18:26 UTC, sevenzing approved these changes

2022-09-05 19:11 UTC, bragov4ik approved these changes

2022-09-05 20:18 UTC, Ilya-Kolomin approved these changes
Review OK👍

2022-09-05 20:18 UTC, Ilya-Kolomin commented on app_go/app.go
> +        http.ListenAndServe(":"+port, mux)
Better practice to add error handling and logging it.

2022-09-05 20:18 UTC, Ilya-Kolomin commented on app_python/README.md
> +    flask run --host=127.0.0.1 --port=5000
Better to not use flask development server for production.

2022-09-06 07:57 UTC, Feyd-Rauth approved these changes

2022-09-06 12:43 UTC, Anatolay requested changes

2022-09-06 12:43 UTC, Anatolay commented on app_go/app.go
> +func indexHandler(w http.ResponseWriter, r *http.Request) {
Avoid single-letter variable names

2022-09-06 12:43 UTC, Anatolay commented on app_python/PYTHON.md
> +* Too simple
What is the disadvantage exactly? Lack of features, lack of extensibility, lack of community support?

2022-09-06 12:43 UTC, Anatolay commented on app_python/app.py
> +    html = "<center>" + moscow_time + "</center>"
Avoid hardcoding html, better use a template engine

2022-09-12 23:04 UTC, closed without merging