Lab2. Iskander Bakhtiyarov
innopolis-devops/labs pull request #84
Opened 2022-09-08 12:51 UTC by Feyd-Rauth

2022-09-10 18:12 UTC, bragov4ik requested changes

2022-09-10 18:12 UTC, bragov4ik commented on app_python/Dockerfile
> +    useradd app -s /bin/sh -d $APP
Maybe it makes sense to set `nologin` as default shell? Docker still allows to execute processes as the user and it appears to be a [good security practice](https://unix.stackexchange.com/questions/155139/does-usr-sbin-nologin-as-a-login-shell-serve-a-security-purpose).

2022-09-12 19:07 UTC, Feyd-Rauth commented on app_python/Dockerfile
> +    useradd app -s /bin/sh -d $APP
But when I will need the ability to execute shell scripts, for instance using shell script for recovering database state, I will have to change shell again to normal.

2022-09-12 20:45 UTC, bragov4ik approved these changes

2022-09-13 07:47 UTC, sevenzing approved these changes

2022-09-13 08:02 UTC, pminina01 approved these changes

2022-09-13 08:05 UTC, Ilya-Kolomin approved these changes
Review OK👍

2022-09-16 20:46 UTC, closed without merging